# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: node:latest
pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
